redis:
  # redis?????(???0)????????3???????????????
  database: 3
  # redis?????????loaclhost?
  host: 127.0.0.1
  # redis??????6379?
  port: 6379
  # redis??????????
  password: root
  # redis????????????
  timeout: 0
  # redis?????
  pool:
    # ???????????8????????
    max-active: 8
    # ???????????8????????
    max-idle: 8
    # ???????????0????????????
    min-idle: 0
    # ???????????????????-1??????????????
    max-wait: -1